# k8s/nginx-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-manual
  labels:
    app: nginx-demo-manual
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo-manual
  template:
    metadata:
      labels:
        app: nginx-demo-manual
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-automatico
spec:
  type: ClusterIP
  selector:
    app: nginx-demo-manual
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
